// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARtsDx8Sm2jY6f7QcwVIFrh8y7g7kkp04',
    appId: '1:378736494263:web:af420fb71af26dc4cc2f32',
    messagingSenderId: '378736494263',
    projectId: 'studyflow-e59c9',
    authDomain: 'studyflow-e59c9.firebaseapp.com',
    storageBucket: 'studyflow-e59c9.firebasestorage.app',
    measurementId: 'G-HG18ZL6W1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtRYzieiAYgfo5Em7EYuSNAxap-emK4Oo',
    appId: '1:378736494263:android:66cb84367ac35574cc2f32',
    messagingSenderId: '378736494263',
    projectId: 'studyflow-e59c9',
    storageBucket: 'studyflow-e59c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDfYjdsp00cwZO9RO6tAUXl3hAVrPQjzg',
    appId: '1:378736494263:ios:41aa798c39fab777cc2f32',
    messagingSenderId: '378736494263',
    projectId: 'studyflow-e59c9',
    storageBucket: 'studyflow-e59c9.firebasestorage.app',
    iosClientId: '378736494263-4stnnm8p938ok7lqk73lmpo21redkvvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDfYjdsp00cwZO9RO6tAUXl3hAVrPQjzg',
    appId: '1:378736494263:ios:41aa798c39fab777cc2f32',
    messagingSenderId: '378736494263',
    projectId: 'studyflow-e59c9',
    storageBucket: 'studyflow-e59c9.firebasestorage.app',
    iosClientId: '378736494263-4stnnm8p938ok7lqk73lmpo21redkvvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARtsDx8Sm2jY6f7QcwVIFrh8y7g7kkp04',
    appId: '1:378736494263:web:1ab59b7bcc573ec3cc2f32',
    messagingSenderId: '378736494263',
    projectId: 'studyflow-e59c9',
    authDomain: 'studyflow-e59c9.firebaseapp.com',
    storageBucket: 'studyflow-e59c9.firebasestorage.app',
    measurementId: 'G-Y39H3S3SBW',
  );
}
